# Generated by Django 2.2.5 on 2019-11-26 10:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('family_name', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(default='images/def_user.png', upload_to='images/')),
                ('teams_link', models.URLField(blank=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=16)),
                ('user_location', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('global_task_info', models.TextField(default=None, max_length=500)),
                ('complete', models.BooleanField(default=False)),
                ('overall_precent_complete', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 11, 26, 12, 14, 47, 775645))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 26, 12, 14, 47, 775645))),
                ('due_date', models.DateTimeField(default=datetime.datetime(2019, 11, 26, 12, 14, 47, 775645))),
                ('task_location', models.CharField(blank=True, max_length=400, null=True)),
                ('task_status', models.CharField(choices=[('ST', 'STARTED'), ('NS', 'NOT STARTED'), ('IP', 'IN PROGRESS'), ('PA', 'PAUSED'), ('CO', 'COMPLETED')], default='NOT STARTED', max_length=2)),
                ('global_task_assign', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='global_task_assign', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=200)),
                ('task_info', models.TextField(blank=True)),
                ('task_complete', models.BooleanField(default=False)),
                ('sub_task', models.CharField(max_length=200)),
                ('task_precent_complete', models.PositiveIntegerField(default=0)),
                ('task_created', models.DateTimeField(default=datetime.datetime(2019, 11, 26, 12, 14, 47, 776625))),
                ('task_updated_at', models.DateTimeField(default=datetime.datetime(2019, 11, 26, 12, 14, 47, 776625))),
                ('task_due_date', models.DateTimeField(default=datetime.datetime(2019, 11, 26, 12, 14, 47, 776625))),
                ('item_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_main', to='ittasks.MainTask')),
                ('task_assign', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
