# Generated by Django 2.2.5 on 2019-09-24 09:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('global_task_info', models.TextField(default=None, max_length=500)),
                ('complete', models.BooleanField(default=False)),
                ('overall_precent_complete', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 9, 24, 12, 41, 0, 99612))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2019, 9, 24, 12, 41, 0, 99612))),
                ('due_date', models.DateTimeField(default=datetime.datetime(2019, 9, 24, 12, 41, 0, 99612))),
                ('global_task_assign', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='global_task_assign', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.CharField(max_length=200)),
                ('task_info', models.TextField(blank=True)),
                ('task_complete', models.BooleanField(default=False)),
                ('sub_task', models.CharField(max_length=200)),
                ('task_precent_complete', models.PositiveIntegerField(default=0)),
                ('task_created', models.DateTimeField(default=datetime.datetime(2019, 9, 24, 12, 41, 0, 100113))),
                ('task_updated_at', models.DateTimeField(default=datetime.datetime(2019, 9, 24, 12, 41, 0, 100113))),
                ('task_due_date', models.DateTimeField(default=datetime.datetime(2019, 9, 24, 12, 41, 0, 100614))),
                ('item_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_main', to='ittasks.MainTask')),
                ('task_assign', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_assign', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
