# Generated by Django 2.2.5 on 2019-10-05 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ittasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintask',
            name='task_status',
            field=models.CharField(choices=[('ST', 'STARTED'), ('NS', 'NOT STARTED'), ('IP', 'IN PROGRESS'), ('PA', 'PAUSED'), ('CO', 'COMPLETED')], default='NOT STARTED', max_length=2),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='task_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 10, 57, 0, 786665)),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='task_due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 10, 57, 0, 786665)),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='task_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 10, 57, 0, 786665)),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 10, 57, 0, 781665)),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 10, 57, 0, 781665)),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 5, 10, 57, 0, 781665)),
        ),
    ]
