# Generated by Django 2.2.7 on 2019-11-23 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ittasks', '0003_auto_20191122_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childtask',
            name='task_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 20, 41, 50, 446660)),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='task_due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 20, 41, 50, 446660)),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='task_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 20, 41, 50, 446660)),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 20, 41, 50, 446660)),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 20, 41, 50, 446660)),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 20, 41, 50, 446660)),
        ),
    ]
