# Generated by Django 2.2.7 on 2019-11-23 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ittasks', '0004_auto_20191123_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childtask',
            name='task_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 20, 56, 48, 347510)),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='task_due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 20, 56, 48, 347510)),
        ),
        migrations.AlterField(
            model_name='childtask',
            name='task_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 20, 56, 48, 347510)),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 20, 56, 48, 347510)),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 20, 56, 48, 347510)),
        ),
        migrations.AlterField(
            model_name='maintask',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 23, 20, 56, 48, 347510)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='images/def_user.png', upload_to='images/'),
        ),
    ]
